services:
  - type: web
    name: cryptron-dynamic
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.0
      - key: PORT
        value: 10000
